<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$siteTitle = $site->title();

$footer_menu = $this->themeSetting('footer_menu');
$footer_copyright = $this->themeSetting('footer_copyright');
$footer_logo2 = $this->themeSetting('logo_bis');
$footer_logo2_label = $this->themeSetting('logo_bis_label');
$footer_logo2_url = $this->themeSetting('logo_bis_url');

$logo = $this->themeSetting('logo');
$logo_small = $this->themeSetting('logo_small');

$socialNetworks  = array( 'facebook', 'x', 'linkedin', 'instagram', 'youtube', 'vimeo', 'mastodon' );
$hasSocialNetworks = false;

foreach ( $socialNetworks as $social_network ) {
	if ( $this->themeSetting( "{$social_network}_url" ) ) {
		$hasSocialNetworks = true;
		break;
	}
}

?>


<footer class="footer">
	<div class="wrap wrap--lg">

		<?php 
			if ($logo_small): 
			?>
			<div class="footer__logo">
				<a href="<?php echo $footer_logo2_url ?>">
					<img src="<?php echo $this->themeSettingAssetUrl('logo_small'); ?>" alt="<?php echo $siteTitle; ?>" />
				</a>
			</div>
		<?php else: ?>
			<div class="footer__logo"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $siteTitle; ?>" /></div>
		<?php endif; ?>

		<?php if( $footer_menu ) : ?>
		<nav class="footer__nav">
			<?php echo $footer_menu; ?>
		</nav>
		<?php endif; ?>

		<!-- Social Networks -->
		<?php if ($hasSocialNetworks) : ?>
			<div class="footer__socials">
				<?php foreach ( $socialNetworks as $social_network ) : ?>
					<?php if ( $social_network_url = $this->themeSetting( "{$social_network}_url" ) ) : ?>
						<a href="<?php echo $social_network_url; ?>">
							<img src="<?php echo $this->assetUrl( "img/{$social_network}.svg" ); ?>"
								alt="<?php echo $escAttr( $social_network ); ?>">
						</a>
					<?php endif; ?>
				<?php endforeach; ?>
			</div>
		<?php endif; ?>

		<?php 
			if ($footer_logo2 && $footer_logo2_label): 
				if($footer_logo2_url):
			?>
			<div class="footer__logo--bis">
				<a href="<?php echo $footer_logo2_url ?>">
					<img src="<?php echo $this->themeSettingAssetUrl('logo_bis'); ?>" alt="<?php echo $footer_logo2_label; ?>" />
				</a>
			</div>
				<?php else: ?>
			<div class="footer__logo--bis"><img src="<?php echo $this->themeSettingAssetUrl('logo_bis'); ?>" alt="<?php echo $footer_logo2_label; ?>" /></div>
			<?php endif; ?>
		<?php endif; ?>

		<?php if( $footer_copyright ) : ?>
		<div class="footer__copyright">
			<?php echo '&copy; '.date('Y'); ?><?php echo ' - '.$footer_copyright; ?>
		</div>
		<?php endif; ?>
	</div>
</footer>
