<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$user = $this->identity();
$siteTitle = $site->title();

$logo = $this->themeSetting('logo');
$logo_small = $this->themeSetting('logo_small');
?>
<header class="header">
	<?php /*if ($this->getHelperPluginManager()->has('languageSwitcher')):*/ ?>
	<div class="header__top">
		<div class="wrap wrap--lg">
			<?php //echo $this->languageSwitcher(); ?>

			<!-- AFFICHAGE DE TEST, À SUPPRIMER AVANT MEP -->

			<ul class="language-switcher locale-flag">
				<li><span class="active" title="français">fr</span></li>
				<li><a href="#" title="English (United States)">en</a></li>
			</ul>
		</div>			
	</div>
	<?php /*endif;*/ ?>

	<div class="wrap wrap--lg">

		<div class="header__logo">
			<a href="<?php echo $site->url(); ?>" class="site-title" class="header__logo--main">
				<?php if ($logo && $logo_small): ?>
					<img class="logo--main" src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
					<img class="logo--small" src="<?php echo $this->themeSettingAssetUrl('logo_small'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
				<?php elseif ($logo): ?>
					<img class="logo--main logo-default" src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
				<?php else: ?>
					<?php echo $escape($siteTitle); ?>
				<?php endif; ?>
			</a>
		</div>

		<div class="header__nav">
			<nav>
				<?php
				echo $site->publicNav()->menu()->renderMenu(null, [
					'maxDepth' => $this->themeSetting('nav_depth') - 1
				]);
				?>
			</nav>
		</div>
	</div>
</header>

<div class="header__search simple-search">
	<div class="wrap wrap--lg">
		<?php echo $this->partial('common/search-form'); ?>
	</div>	
	<div class="page-banner"></div>
</div>