<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$siteTitle = $site->title();

	$themes_title = $this->themeSetting('home_themes_title');
	$themes_text = $this->themeSetting('home_themes_text');
	$themes_label = $this->themeSetting('home_themes_label');
	$themes_url = $this->themeSetting('home_themes_url');
?>	
<section class="home-themes">
	<div class="wrap wrap--lg">

		<h2 class="home-themes__title">
			<div class="home-themes__title__container"><?php if( $themes_title ): echo $themes_title; else: echo $translate('Discover other items'); endif; ?></div>
		</h2>

		<?php if( $themes_text ): echo '<div class="home-themes__text wrap wrap--sm">'.$themes_text.'</div>';  endif; ?>

		<ul class="home-themes__list">
			<?php
			for($numTheme=1; $numTheme<=10; $numTheme++):
			
				$theme_title = $this->themeSetting('theme_title'.$numTheme);
				$theme_url = $this->themeSetting('theme_url'.$numTheme);

				if ($theme_title && $theme_url):
					$theme = '<a href="'.$theme_url.'" target="_blank" title="'.$theme_title.'"><h3>'.$theme_title.'</h3></a>';
				?>
				<li class="home-themes__item">
					<?php echo $theme; ?>
				</li>

				<?php 
				endif;
			endfor; 
			?>
		</ul>
		<?php if ($themes_label && $themes_url): ?>
		<div class="button__container">
			<a href="<?php echo $themes_url; ?>" class="button button--small"><?php echo $themes_label; ?></a>
		</div>
		<?php endif; ?>
	</div>
</section>