<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'items search');
?>
<div class="breadcrumbs wrap wrap--lg">
	<a href="<?php echo $this->url('site', [], [], true); ?>"><?php echo $translate('Home'); ?></a> &gt; <span><?php echo $translate('Advanced item search'); ?></span>
</div>
<div class="wrap wrap--md">
	<div class="page-title"><h1 class="page-title"><span class="title"><?php echo $translate('Advanced item search'); ?></span></h1></div>
</div>
<div class="wrap wrap--md">
	<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
	<?php echo $this->partial(
		'common/advanced-search',
		['query' => $this->params()->fromQuery(), 'resourceType' => 'item']
	); ?>
	<div id="page-actions">
		<input type="submit" name="submit" value="<?php echo $this->escapeHtml($translate('Search')); ?>">
	</div>
	</form>

</div>

