<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;


// Regions
$mainBlockContent = $this->resourcePageBlocks($item);
$mainHasBlocks = $mainBlockContent->hasBlocks();

$bottomBlockContent = $this->resourcePageBlocks($item, 'bottom');
$bottomHasBlocks = $bottomBlockContent->hasBlocks();

// Metadata contents
$itemdataChapoHTML = '';
if ($itemdataChapo = $this->themeSetting( 'itemdata_chapo' )) {
	$itemdataChapoHTML = $this->DisplaySelectedValues($item, $itemdataChapo, true, false, '');
}

$itemdataInfosHTML = '';
if ($itemdataInfos = $this->themeSetting( 'itemdata_infos' )) {
	$itemdataInfosHTML = $this->DisplaySelectedValues($item, $itemdataInfos, true);
}

$itemdataEditoHTML = '';
if ($itemdataEdito = $this->themeSetting( 'itemdata_edito' )) {
	$itemdataEditoTitle = $this->themeSetting( 'itemdata_edito_title' );
	$itemdataEditoHTML = $this->DisplaySelectedValues($item, $itemdataEdito, true, true, '');
}

$itemdataCiteHTML = '';
if ($itemdataCite = $this->themeSetting( 'itemdata_cite' )) {
	$itemdataCiteHTML = $this->DisplaySelectedValues($item, $itemdataCite, true, true, '');
}

$itemdataRelationHTML = '';
if ($itemdataRelation = 'dcterms:relation') {
	$itemdataRelationTitle = $translate( 'Related resources' );
	$itemdataRelationHTML = $this->DisplaySelectedValues($item, $itemdataRelation, true, false, '');
}


?>

<?php
// Static breadcrumb with link to faceted browse page
$breadcrumbParentLink = '/faceted-browse/1';
$breadcrumbParentLinkTitle = 'Objets';
$breadcrumbParents = '<a href="'.$this->url('site', [], [], true).$escape($breadcrumbParentLink).'">'.$escape($breadcrumbParentLinkTitle).'</a>';
?>
<nav class="breadcrumbs wrap wrap--lg"><a href="<?php echo $this->url('site', [], [], true); ?>"><?php echo $translate('Home'); ?></a> &gt; <?php echo $breadcrumbParents; ?> &gt; <span><?php echo $item->displayTitle(); ?></span></nav>

<div class="blocks">

	<?php if ($this->getHelperPluginManager()->has('shareMeBaby')) : ?>
		<div class="block-share-me-baby"><div class="wrap wrap--lg"><?php echo $this->shareMeBaby(); ?></div></div>
	<?php endif; ?>

	<div class="page-title"><?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 1); ?></div>

	<?php if ($itemdataChapoHTML): ?>
		<div class="wrap wrap--xs page-chapo">
			<?php echo $itemdataChapoHTML; ?>
		</div>
	<?php endif; ?>

	<div class="wrap wrap--lg">

		<?php $this->trigger('view.show.before'); ?>

		<?php if ($mainHasBlocks && $blockContent = $mainBlockContent->getBlocks()): ?>
			<div class="main-region">
				<div class="metadata">
					<?php echo $blockContent; ?>
				</div>
			</div>
		<?php endif; ?>

		<div class="regions-container">

			<div class="regions-container-col1">
				<?php if ( $itemdataInfosHTML ): ?>
					<div class="region region--section section--infos">
						<div class="metadata">
							<?php
							// Affichage métadonnées section Infos
							echo ($itemdataInfosHTML) ? '<div class="properties-wrapper">'.$itemdataInfosHTML.'</div>' : '';
							?>
						</div>
					</div>
				<?php endif; ?>

				<?php if ($itemdataEditoHTML): ?>
					<div class="region region--section section--edito">
						<?php
						// Affichage titre section Infos
						echo ($itemdataEditoTitle) ? '<p class="section--edito__title h2">'.$itemdataEditoTitle.'</p>' : '';
						?>
						<?php
						// Affichage métadonnées section Edito
						echo ($itemdataEditoHTML) ? '<div class="properties-wrapper">'.$itemdataEditoHTML.'</div>' : '';
						?>
					</div>
				<?php endif; ?>

				<?php if ($itemdataCiteHTML): ?>
					<div class="region region--section section--cite">
						<?php
						// Affichage métadonnées section Citation
						echo ($itemdataCiteHTML) ? '<div class="properties-wrapper">'.$itemdataCiteHTML.'</div>' : '';
						?>
					</div>
				<?php endif; ?>
			</div>

			<div class="regions-container-col2">
				<?php if ($itemdataRelationHTML): ?>
					<div class="region region--section section--relation">
						<div class="metadata">
							<?php
							// Affichage titre section Relation
							echo ($itemdataRelationTitle) ? '<p class="section--relation__title h2">'.$itemdataRelationTitle.'</p>' : '';
							?>
							<?php
							// Affichage métadonnées section Relation
							echo ($itemdataRelationHTML) ? '<div class="properties-wrapper">'.$itemdataRelationHTML.'</div>' : '';
							?>
						</div>
					</div>
				<?php endif; ?>
			</div>

		</div>

		<?php if ($bottomHasBlocks && $blockContent = $bottomBlockContent->getBlocks()): ?>
			<div class="bottom-region">
				<div class="wrap wrap--md">
					<div class="metadata">
						<?php echo $blockContent; ?>
					</div>
				</div>
			</div>
		<?php endif; ?>

		<?php $this->trigger('view.show.after'); ?>

	</div>

</div>

<script type="text/javascript">
$(document).ready(function() {
	$('body .regions-container a').each(function() {
		var href = $(this).attr('href');
		// Vérifie si le lien commence par http ou https et s'il ne provient pas du même domaine
		if (href && href.indexOf('http') === 0 && this.hostname !== window.location.hostname) {
			$(this).attr('target', '_blank'); // Ajoute target="_blank"
			$(this).attr('title', '<?php echo $translate('Open new tab'); ?>'); // Ajoute un titre
			$(this).append('<i class="fas fa-external-link-square-alt"></i>'); // Ajoute l'icône après le libellé du lien
		}
	});
/*
	$('body .regions-container a.resource-link').each(function() {
		var href = $(this).attr('href');
		if (this.hostname == window.location.hostname) {
			$(this).find('img').remove(); // Supprime les images
			$(this).append('<i class="o-icon-uri"></i>'); // Ajoute l'icône après le libellé du lien
		}
	});
*/

});
</script>