<?php
$translate = $this->plugin('translate');
$item = $media->item();
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'media resource show'); 
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
?>

<nav class="breadcrumbs wrap wrap--lg"><a href="<?php echo $this->url('site', [], [], true); ?>"><?php echo $translate('Home'); ?></a> &gt; <span><?php echo $media->displayTitle(null, $valueLang); ?></span></nav>
<div class="blocks">
	<div class="wrap wrap--lg">
		<div class="page-title"><?php echo $this->pageTitle($media->displayTitle(null, $valueLang), 1); ?></div>
		<h3><?php echo $translate('Media'); ?></h3>
		<?php $this->trigger('view.show.before'); ?>
		<p class="media-parent-item">
			<?php echo sprintf($translate('Part of %s'), $item->link($item->displayTitle(null, $valueLang))); ?>
		</p>
		<?php echo $this->resourcePageBlocks($media)->getBlocks(); ?>
		<?php $this->trigger('view.show.after'); ?>
	</div>
</div>