<div class="browse-controls">
	<div class="pagination__container"><?php echo $this->pagination(); ?></div>
	<?php echo $this->sortSelector($sortings); ?>
</div>
<?php if ($items): ?>
<?php echo $this->partial($columns ? 'browse-items-columns' : 'browse-items-default'); ?>
<?php else: ?>
<p><?php echo $this->translate('There are no results.'); ?></p>
<?php endif; ?>
<div class="browse-controls">
	<div class="pagination__container"><?php echo $this->pagination(); ?></div>
</div>
