<?php
$translate = $this->plugin('translate');
$BannerHome = $this->themeSettingAssetUrl('banner_large');
$BannerHomeSmall = $this->themeSettingAssetUrl('banner_home_small');
$BannerEdito = $this->themeSettingAssetUrl('banner_edito');
$BannerItems = $this->themeSettingAssetUrl('banner_items');
$BannerItemsets = $this->themeSettingAssetUrl('banner_itemsets');
$BannerFacetBrowse = $this->themeSettingAssetUrl('banner_facetbrowse');
$BannerSearch = $this->themeSettingAssetUrl('banner_search');
$FooterSeparator = $this->themeSettingAssetUrl('footer_separator');
$separator = $this->themeSettingAssetUrl('separator');
$userBar = $this->userBar();

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' | ');

$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('lib/splide/css/splide.min.css' ));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));

$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('lib/splide/js/splide.min.js' ));
$this->headScript()->appendFile($this->assetUrl('js/theme.js'));

$this->jsTranslate();
$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>


		<style type="text/css" media="screen">
			:root {
				<?php echo ($BannerHome) ? '--img-banner-home: url('.$BannerHome.');' : '' ; ?>
				<?php 
				if($BannerHomeSmall) : 
					echo '--img-banner-home-small: url('.$BannerHomeSmall.')';
				elseif($BannerHome):
					echo '--img-banner-home-small: url('.$BannerHome.')';
				endif;
				?>
				<?php echo ($BannerEdito) ? '--img-banner-edito: url('.$BannerEdito.');' : '' ; ?>
				<?php echo ($BannerItems) ? '--img-banner-items: url('.$BannerItems.');' : '' ; ?>
				<?php echo ($BannerItemsets) ? '--img-banner-itemsets: url('.$BannerItemsets.');' : '' ; ?>
				<?php echo ($BannerFacetBrowse) ? '--img-banner-facetbrowse: url('.$BannerFacetBrowse.');' : '' ; ?>
				<?php echo ($BannerSearch) ? '--img-banner-search: url('.$BannerSearch.');' : '' ; ?>
				<?php echo ($FooterSeparator) ? '--img-footer-separator: url('.$FooterSeparator.');' : '' ; ?>
				<?php echo ($separator) ? '--img-separator: url('.$separator.');' : '' ; ?>
			}
		</style>
	</head>

	<?php echo $this->htmlElement('body')->appendAttribute('class', 'minimal'); ?>
		<?php echo $userBar; ?>

		<?php echo $this->partial('common/theme/header', ['userBar' => $userBar, 'site' => $site]); ?>

		<div id="content" role="main">
			<?php echo $this->messages(); ?>
			<?php echo $this->content; ?>
		</div>
		
		<?php
			// Show partners section on all pages
			$partners_show = $this->themeSetting( 'partners_show');
			$partners_show_allpages = $this->themeSetting( 'partners_show_allpages');

			if( ($partners_show == 1) && ($partners_show_allpages == 1) ):
				echo $this->partial('common/theme/partners', ['site' => $site, 'translate' => $translate]);
			endif;
		?>
		<?php echo $this->partial('common/theme/footer', ['site' => $site]); ?>
		<?php echo $this->partial('common/theme/back-to-top', ['translate' => $translate]); ?>
	</body>
</html>
